// <auto-generated />
using GameLand.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLand.DataAccess.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230803161924_AddCategoryTable")]
    partial class AddCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameLand.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "null",
                            Name = "Игровые ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Description = "null",
                            Name = "Игровые системные блоки"
                        },
                        new
                        {
                            Id = 3,
                            Description = "null",
                            Name = "Игровые мониторы"
                        },
                        new
                        {
                            Id = 4,
                            Description = "null",
                            Name = "Консоли PlayStation 5"
                        },
                        new
                        {
                            Id = 5,
                            Description = "null",
                            Name = "Игры для PlayStation 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "null",
                            Name = "Аксессуары для PlayStation 5"
                        },
                        new
                        {
                            Id = 7,
                            Description = "null",
                            Name = "Игры для PlayStation 4"
                        },
                        new
                        {
                            Id = 8,
                            Description = "null",
                            Name = "Аксессуары для PlayStation 4"
                        },
                        new
                        {
                            Id = 9,
                            Description = "null",
                            Name = "Клавиатуры"
                        },
                        new
                        {
                            Id = 10,
                            Description = "null",
                            Name = "Мышки"
                        },
                        new
                        {
                            Id = 11,
                            Description = "null",
                            Name = "Гарнитура"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
