// <auto-generated />
using System;
using GameLand.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLand.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameLand.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "#A1",
                            Description = "null",
                            Name = "Игровые ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Code = "#A2",
                            Description = "null",
                            Name = "Игровые системные блоки"
                        },
                        new
                        {
                            Id = 3,
                            Code = "#A3",
                            Description = "null",
                            Name = "Игровые мониторы"
                        },
                        new
                        {
                            Id = 4,
                            Code = "#B1",
                            Description = "null",
                            Name = "Консоли PlayStation 5"
                        },
                        new
                        {
                            Id = 5,
                            Code = "#B2",
                            Description = "null",
                            Name = "Игры для PlayStation 5"
                        },
                        new
                        {
                            Id = 6,
                            Code = "#B3",
                            Description = "null",
                            Name = "Аксессуары для PlayStation 5"
                        },
                        new
                        {
                            Id = 7,
                            Code = "#C1",
                            Description = "null",
                            Name = "Игры для PlayStation 4"
                        },
                        new
                        {
                            Id = 8,
                            Code = "#C2",
                            Description = "null",
                            Name = "Аксессуары для PlayStation 4"
                        },
                        new
                        {
                            Id = 9,
                            Code = "#D1",
                            Description = "null",
                            Name = "Клавиатуры"
                        },
                        new
                        {
                            Id = 10,
                            Code = "#E1",
                            Description = "null",
                            Name = "Мышки"
                        },
                        new
                        {
                            Id = 11,
                            Code = "#F1",
                            Description = "null",
                            Name = "Гарнитура"
                        });
                });

            modelBuilder.Entity("GameLand.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OldPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "400135845",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\42e671bd-1d26-4343-b859-4f39e39610b1.jpg",
                            Name = "Ноутбук игровой Thunderobot 911 M G3 Pro JT009M00BRU",
                            OldPrice = 129999.0,
                            Price = 114999.0
                        },
                        new
                        {
                            Id = 2,
                            Article = "400079994",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\279ab8fe-f947-46f9-93f1-340e2fe1f25e.jpg",
                            Name = "Ноутбук игровой Thunderobot 911 Air Wave D",
                            OldPrice = 85999.0,
                            Price = 59999.0
                        },
                        new
                        {
                            Id = 3,
                            Article = "400132672",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\0d58f316-aca3-4251-87c3-90a24423fd40.jpg",
                            Name = "Ноутбук игровой Thunderobot 911 Plus G3 Pro JT009R00BRU",
                            OldPrice = 134999.0,
                            Price = 124999.0
                        },
                        new
                        {
                            Id = 4,
                            Article = "30067633",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\1061ae0b-ea1f-493a-855a-2db6ba232fd4.jpg",
                            Name = "Ноутбук игровой ASUS TUF Dash F15 FX517ZM-HN157",
                            OldPrice = 105999.0,
                            Price = 99999.0
                        },
                        new
                        {
                            Id = 5,
                            Article = "400156623",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\9a5c7945-37a3-4c9a-8f5e-0004af0be8e9.jpg",
                            Name = "Ноутбук игровой Thunderobot 911 Air XS D",
                            OldPrice = 0.0,
                            Price = 69999.0
                        },
                        new
                        {
                            Id = 6,
                            Article = "30067660",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\65149011-d425-4105-9606-46feab01df54.jpg",
                            Name = "Ноутбук игровой MSI GF63 Thin 11UC-255XRU",
                            OldPrice = 69999.0,
                            Price = 62999.0
                        },
                        new
                        {
                            Id = 7,
                            Article = "30066169",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\8bb94d52-a4d5-4ebc-a159-e8032cfa775f.jpg",
                            Name = "Ноутбук игровой Thunderobot 911 MT Pro D",
                            OldPrice = 111999.0,
                            Price = 89999.0
                        },
                        new
                        {
                            Id = 8,
                            Article = "30067313",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\0d1e2c6b-3b80-4e80-af0c-5d81feedecab.jpg",
                            Name = "Ноутбук игровой MSI Raider GE78 HX 13VI-206RU (MS-17S1)",
                            OldPrice = 429999.0,
                            Price = 364999.0
                        },
                        new
                        {
                            Id = 9,
                            Article = "400132671",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\821d9e89-7309-4e1f-9327-9f923ecfb503.jpg",
                            Name = "Ноутбук игровой Thunderobot Zero G3 Ultra Orange JT009N00BRU",
                            OldPrice = 0.0,
                            Price = 299999.0
                        },
                        new
                        {
                            Id = 10,
                            Article = "4212284",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\97cd125b-4d27-4b41-a58b-4e6abd27a275.jpg",
                            Name = "Ноутбук игровой Thunderobot Zero Ultra XT",
                            OldPrice = 0.0,
                            Price = 279999.0
                        },
                        new
                        {
                            Id = 11,
                            Article = "30066473",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\a43d2a2d-1432-4be7-989f-ab8acee69a1f.jpg",
                            Name = "Ноутбук игровой MSI Raider GE77HX 12UGS-221RU",
                            OldPrice = 269999.0,
                            Price = 229999.0
                        },
                        new
                        {
                            Id = 12,
                            Article = "4212282",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "\\images\\product\\cd6a28a8-9c77-41a2-b70a-d433357a06e2.jpg",
                            Name = "Ноутбук игровой Thunderobot Zero Ultra 7 Yellow",
                            OldPrice = 249999.0,
                            Price = 219999.0
                        },
                        new
                        {
                            Id = 13,
                            Article = "30065216",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\761857a3-5184-4090-b72b-1768f9c41772.jpg",
                            Name = "Системный блок игровой Acer Predator PO3-630",
                            OldPrice = 129999.0,
                            Price = 99999.0
                        },
                        new
                        {
                            Id = 14,
                            Article = "30064738",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\49ac2be4-3547-43f7-9c61-dd39cb5450be.jpg",
                            Name = "Системный блок игровой MSI AEGIS Ti5",
                            OldPrice = 332499.0,
                            Price = 299999.0
                        },
                        new
                        {
                            Id = 15,
                            Article = "30064736",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\f83a65f0-134b-439d-a6a0-7e2a5a8a72ad.jpg",
                            Name = "Системный блок игровой MSI MAG Codex X5",
                            OldPrice = 0.0,
                            Price = 247499.0
                        },
                        new
                        {
                            Id = 16,
                            Article = "30064351",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\6b4ea99d-7c4f-495d-b042-088bd3f840c4.jpg",
                            Name = "Системный блок игровой MUST MBM117",
                            OldPrice = 159999.0,
                            Price = 129999.0
                        },
                        new
                        {
                            Id = 17,
                            Article = "30066255",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\7606ce80-49bd-4dda-813c-3d7bc32c6975.jpg",
                            Name = "Системный блок игровой Thunderobot BW IV Max D",
                            OldPrice = 174999.0,
                            Price = 129999.0
                        },
                        new
                        {
                            Id = 18,
                            Article = "400089344",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\07cc637e-6cd2-477d-9b72-5b4641f37f39.jpg",
                            Name = "Системный блок игровой Thunderobot Black Warrior V Shark 7",
                            OldPrice = 0.0,
                            Price = 299999.0
                        },
                        new
                        {
                            Id = 19,
                            Article = "30065807",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\12131301-6594-4936-9e85-1e9c45ae7937.jpg",
                            Name = "Системный блок игровой Raskat STRIKE 520 107290",
                            OldPrice = 86999.0,
                            Price = 81999.0
                        },
                        new
                        {
                            Id = 20,
                            Article = "400156700",
                            CategoryId = 2,
                            Description = "null",
                            ImageURL = "\\images\\product\\3c6fadf6-2f30-4c41-97ba-93ad753d3b1b.jpg",
                            Name = "Системный блок игровой 4Aces Royal Flush",
                            OldPrice = 249999.0,
                            Price = 234999.0
                        },
                        new
                        {
                            Id = 21,
                            Article = "400095426",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\dcc68fcb-4661-4099-95a1-9dff72dae6c5.jpg",
                            Name = "Монитор игровой Thunderobot KU48F120E",
                            OldPrice = 124999.0,
                            Price = 99999.0
                        },
                        new
                        {
                            Id = 22,
                            Article = "400086711",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\6d341196-9ff3-476e-bb44-768253bee6c7.jpg",
                            Name = "Монитор игровой Samsung Odyssey Neo G7 S43CG700NI",
                            OldPrice = 89999.0,
                            Price = 82999.0
                        },
                        new
                        {
                            Id = 23,
                            Article = "400095283",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\748ed21e-74c9-4d74-afab-316bc14c0597.jpg",
                            Name = "Монитор игровой Thunderobot KU27F144M",
                            OldPrice = 79999.0,
                            Price = 74999.0
                        },
                        new
                        {
                            Id = 24,
                            Article = "400095286",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\b3a9764e-2c1d-4fbd-a4f3-ef33a6a3b86c.jpg",
                            Name = "Монитор игровой Thunderobot KQ34C144C",
                            OldPrice = 39999.0,
                            Price = 37999.0
                        },
                        new
                        {
                            Id = 25,
                            Article = "400095371",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\bc8bd696-60e0-44dd-a08e-65248563ff21.jpg",
                            Name = "Монитор игровой Thunderobot KF27C240L",
                            OldPrice = 0.0,
                            Price = 21999.0
                        },
                        new
                        {
                            Id = 26,
                            Article = "400155883",
                            CategoryId = 3,
                            Description = "null",
                            ImageURL = "\\images\\product\\abc69ff0-a2ec-42dc-9b25-38303524c7c6.jpg",
                            Name = "Монитор игровой Thunderobot DF27C240L",
                            OldPrice = 23999.0,
                            Price = 19999.0
                        },
                        new
                        {
                            Id = 27,
                            Article = "40078904",
                            CategoryId = 4,
                            Description = "null",
                            ImageURL = "\\images\\product\\f9c6eb3d-78c4-42de-aba4-a81fc6b04835.jpg",
                            Name = "Консоль Sony PlayStation 5 Blu-Ray Edition CFI-12(00/16/18)A",
                            OldPrice = 0.0,
                            Price = 59999.0
                        },
                        new
                        {
                            Id = 28,
                            Article = "40079571",
                            CategoryId = 4,
                            Description = "null",
                            ImageURL = "\\images\\product\\65f10155-3b20-4a05-b3e0-f42f33b953f5.jpg",
                            Name = "Игровая приставка Sony PlayStation 5 Digital Edition CFI-1200B",
                            OldPrice = 0.0,
                            Price = 52999.0
                        },
                        new
                        {
                            Id = 29,
                            Article = "400122205",
                            CategoryId = 4,
                            Description = "null",
                            ImageURL = "\\images\\product\\10215343-9415-4c9f-b184-6ea93ae3200b.jpg",
                            Name = "Игровая консоль PS5 Sony CFI-1200",
                            OldPrice = 0.0,
                            Price = 60190.0
                        },
                        new
                        {
                            Id = 30,
                            Article = "400122205",
                            CategoryId = 4,
                            Description = "null",
                            ImageURL = "\\images\\product\\3f9df10a-0e34-45fa-aa07-be6440520376.jpg",
                            Name = "Игровая консоль PS5 Sony Playstation 5 Digital Edition",
                            OldPrice = 0.0,
                            Price = 62390.0
                        },
                        new
                        {
                            Id = 31,
                            Article = "6020103",
                            CategoryId = 5,
                            Description = "null",
                            ImageURL = "\\images\\product\\bae42bf4-6c57-4fc2-a54a-4986145fa904.jpg",
                            Name = "PS5 Electronic Arts FIFA 23",
                            OldPrice = 7199.0,
                            Price = 2159.0
                        },
                        new
                        {
                            Id = 32,
                            Article = "6020101",
                            CategoryId = 5,
                            Description = "null",
                            ImageURL = "\\images\\product\\ec34da26-8d70-420a-bc8a-8d43551878fa.jpg",
                            Name = "S5 Warner Bros. IE Mortal Kombat 11 Standard",
                            OldPrice = 3199.0,
                            Price = 899.0
                        },
                        new
                        {
                            Id = 33,
                            Article = "400081693",
                            CategoryId = 5,
                            Description = "null",
                            ImageURL = "\\images\\product\\fb8da971-afe0-49dd-8843-62c2096c2677.jpg",
                            Name = "PS5 игра Focus Home Atomic Heart",
                            OldPrice = 0.0,
                            Price = 5999.0
                        },
                        new
                        {
                            Id = 34,
                            Article = "400171614",
                            CategoryId = 5,
                            Description = "null",
                            ImageURL = "\\images\\product\\9869d232-49a6-4009-a6ad-3b193b48266a.jpg",
                            Name = "PS5 игра Electronic Arts EA Sports FC 24",
                            OldPrice = 0.0,
                            Price = 8999.0
                        },
                        new
                        {
                            Id = 35,
                            Article = "400177672",
                            CategoryId = 5,
                            Description = "null",
                            ImageURL = "\\images\\product\\ea3dfe08-8d17-4394-8400-7c3c573db38d.jpg",
                            Name = "PS5 игра Sony Marvel's Spider-Man 2",
                            OldPrice = 0.0,
                            Price = 9999.0
                        },
                        new
                        {
                            Id = 36,
                            Article = "40076710",
                            CategoryId = 6,
                            Description = "null",
                            ImageURL = "\\images\\product\\c6c055b5-b7ff-4460-a84a-697846c80dd2.jpg",
                            Name = "Набор кнопок для геймпада PS5 Red Line 5в1",
                            OldPrice = 0.0,
                            Price = 1399.0
                        },
                        new
                        {
                            Id = 37,
                            Article = "400012658",
                            CategoryId = 6,
                            Description = "null",
                            ImageURL = "\\images\\product\\78656946-fa32-4ce3-9d21-1b35419cf4f8.jpg",
                            Name = "Кронштейн для игровых консолей PlayStation 5 HOOK HOOK PS5",
                            OldPrice = 0.0,
                            Price = 2190.0
                        },
                        new
                        {
                            Id = 38,
                            Article = "400171569",
                            CategoryId = 7,
                            Description = "null",
                            ImageURL = "\\images\\product\\1bb19a42-9077-49d4-936e-daf8ee3c736f.jpg",
                            Name = "PS4 игра Electronic Arts EA Sports FC 24",
                            OldPrice = 0.0,
                            Price = 8999.0
                        },
                        new
                        {
                            Id = 39,
                            Article = "400081648",
                            CategoryId = 7,
                            Description = "null",
                            ImageURL = "\\images\\product\\e800ecbb-d315-4a88-acaf-5515e42a5ad5.jpg",
                            Name = "PS4 игра Focus Home Atomic Heart",
                            OldPrice = 0.0,
                            Price = 5399.0
                        },
                        new
                        {
                            Id = 40,
                            Article = "40074581",
                            CategoryId = 7,
                            Description = "null",
                            ImageURL = "\\images\\product\\ae2b4834-5360-46fb-b58e-ea9a0102dd4c.jpg",
                            Name = "PS4 игра Sony Marvel's Человек-Паук: Майлз Моралес",
                            OldPrice = 0.0,
                            Price = 4299.0
                        },
                        new
                        {
                            Id = 41,
                            Article = "40079473",
                            CategoryId = 8,
                            Description = "null",
                            ImageURL = "\\images\\product\\a71f1821-fae8-41ab-9ba1-8066737addb6.jpg",
                            Name = "Геймпад для консоли PlayStation 4 DualShock 4 v2 White",
                            OldPrice = 0.0,
                            Price = 6499.0
                        },
                        new
                        {
                            Id = 42,
                            Article = "40065372",
                            CategoryId = 8,
                            Description = "null",
                            ImageURL = "\\images\\product\\d194d5f1-3c84-437c-81d9-6af1a4aca615.jpg",
                            Name = "Геймпад для консоли PS4 PlayStation 4 DualShock 4 v2 Black",
                            OldPrice = 0.0,
                            Price = 6999.0
                        },
                        new
                        {
                            Id = 43,
                            Article = "400012646",
                            CategoryId = 8,
                            Description = "null",
                            ImageURL = "\\images\\product\\97864b5b-d5bd-4654-a971-e8e6dc6a198c.jpg",
                            Name = "Кронштейн для игровых консолей PlayStation 4",
                            OldPrice = 0.0,
                            Price = 1980.0
                        },
                        new
                        {
                            Id = 44,
                            Article = "50174790",
                            CategoryId = 9,
                            Description = "null",
                            ImageURL = "\\images\\product\\fc12df68-cc87-416c-8644-729d338b3469.jpg",
                            Name = "Игровая клавиатура Logitech G715 Aurora Collection Linear",
                            OldPrice = 0.0,
                            Price = 25999.0
                        },
                        new
                        {
                            Id = 45,
                            Article = "50141080",
                            CategoryId = 9,
                            Description = "null",
                            ImageURL = "\\images\\product\\7fffb182-2443-440c-8353-94262a0a195f.jpg",
                            Name = "Игровая клавиатура Logitech G915 TKL LIGHTSPEED Wireless RGB",
                            OldPrice = 0.0,
                            Price = 20499.0
                        },
                        new
                        {
                            Id = 46,
                            Article = "50141080",
                            CategoryId = 9,
                            Description = "null",
                            ImageURL = "\\images\\product\\ef005796-ef47-4619-8c82-50bd30791e95.jpg",
                            Name = "Игровая клавиатура Red Square Keyrox TKL g3ms White",
                            OldPrice = 0.0,
                            Price = 11345.0
                        },
                        new
                        {
                            Id = 47,
                            Article = "50167104",
                            CategoryId = 9,
                            Description = "null",
                            ImageURL = "\\images\\product\\6ef5baa8-8cc5-4e76-ae8d-02248841d386.jpg",
                            Name = "Игровая клавиатура Red Square Keyrox Classic Pro",
                            OldPrice = 0.0,
                            Price = 6999.0
                        },
                        new
                        {
                            Id = 48,
                            Article = "50175828",
                            CategoryId = 10,
                            Description = "null",
                            ImageURL = "\\images\\product\\a43c6909-c1bb-45b3-aaea-f8d6f454673f.jpg",
                            Name = "Игровая мышь Logitech G502 X LIGHTSPEED White",
                            OldPrice = 0.0,
                            Price = 11499.0
                        },
                        new
                        {
                            Id = 49,
                            Article = "50175847",
                            CategoryId = 10,
                            Description = "null",
                            ImageURL = "\\images\\product\\79d33e76-c25a-4097-b33d-81d51858c5dc.jpg",
                            Name = "Игровая мышь HyperX Pulsefire Haste Wireless White",
                            OldPrice = 0.0,
                            Price = 6999.0
                        },
                        new
                        {
                            Id = 50,
                            Article = "50173476",
                            CategoryId = 10,
                            Description = "null",
                            ImageURL = "\\images\\product\\7178780d-d0e0-4cc0-bec6-c8c79d55a5b8.jpg",
                            Name = "Игровая мышь Logitech G703",
                            OldPrice = 0.0,
                            Price = 8799.0
                        },
                        new
                        {
                            Id = 51,
                            Article = "50175523",
                            CategoryId = 11,
                            Description = "null",
                            ImageURL = "\\images\\product\\4a7fe03e-6ee1-4d97-94c9-afc68150a83c.jpg",
                            Name = "Игровые наушники Logitech G733 Lightspeed Lilac",
                            OldPrice = 0.0,
                            Price = 17599.0
                        },
                        new
                        {
                            Id = 52,
                            Article = "50175813",
                            CategoryId = 11,
                            Description = "null",
                            ImageURL = "\\images\\product\\7d9be698-a312-466e-bb89-f912559264a9.jpg",
                            Name = "Игровые наушники HyperX Cloud Alpha S",
                            OldPrice = 0.0,
                            Price = 11499.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GameLand.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("GameLand.Models.Product", b =>
                {
                    b.HasOne("GameLand.Models.Category", "Category_of_product")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_of_product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
