// <auto-generated />
using GameLand.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLand.DataAccess.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameLand.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "#A1",
                            Description = "null",
                            Name = "Игровые ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Code = "#A2",
                            Description = "null",
                            Name = "Игровые системные блоки"
                        },
                        new
                        {
                            Id = 3,
                            Code = "#A3",
                            Description = "null",
                            Name = "Игровые мониторы"
                        },
                        new
                        {
                            Id = 4,
                            Code = "#B1",
                            Description = "null",
                            Name = "Консоли PlayStation 5"
                        },
                        new
                        {
                            Id = 5,
                            Code = "#B2",
                            Description = "null",
                            Name = "Игры для PlayStation 5"
                        },
                        new
                        {
                            Id = 6,
                            Code = "#B3",
                            Description = "null",
                            Name = "Аксессуары для PlayStation 5"
                        },
                        new
                        {
                            Id = 7,
                            Code = "#C1",
                            Description = "null",
                            Name = "Игры для PlayStation 4"
                        },
                        new
                        {
                            Id = 8,
                            Code = "#C2",
                            Description = "null",
                            Name = "Аксессуары для PlayStation 4"
                        },
                        new
                        {
                            Id = 9,
                            Code = "#D1",
                            Description = "null",
                            Name = "Клавиатуры"
                        },
                        new
                        {
                            Id = 10,
                            Code = "#E1",
                            Description = "null",
                            Name = "Мышки"
                        },
                        new
                        {
                            Id = 11,
                            Code = "#F1",
                            Description = "null",
                            Name = "Гарнитура"
                        });
                });

            modelBuilder.Entity("GameLand.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OldPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "A234jr2j324",
                            CategoryId = 1,
                            Description = "null",
                            ImageURL = "",
                            Name = "Ноутбук игровой Thunderobot 911 M G3 Pro JT009M00BRU",
                            OldPrice = 129999.0,
                            Price = 114999.0
                        },
                        new
                        {
                            Id = 2,
                            Article = "D8ffb7bgffsf",
                            CategoryId = 4,
                            Description = "null",
                            ImageURL = "",
                            Name = "Консоль Sony PlayStation 5 Blu-Ray Edition CFI-12(00/16/18)A",
                            OldPrice = 0.0,
                            Price = 59999.0
                        });
                });

            modelBuilder.Entity("GameLand.Models.Product", b =>
                {
                    b.HasOne("GameLand.Models.Category", "Category_of_product")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_of_product");
                });
#pragma warning restore 612, 618
        }
    }
}
